<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Configurations>Debug;Release;Production</Configurations>
<!--         <NoWarn></NoWarn>-->
        <ImplicitUsings>enable</ImplicitUsings>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <Deterministic>true</Deterministic>
        <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
        <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
        <RunAnalyzersDuringLiveAnalysis>True</RunAnalyzersDuringLiveAnalysis>
        <RunAnalyzersDuringBuild>True</RunAnalyzersDuringBuild>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
        <EnableNETAnalyzers>True</EnableNETAnalyzers>
        <Optimize>True</Optimize>
    </PropertyGroup>
</Project>